name: Deploy Trimly to EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    environment: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVICE_HOST }}
          username: ${{ secrets.SERVICE_USER }}
          key: ${{ secrets.SERVICE_KEY }}
          script: |
            echo "Connected to EC2"
            bash /home/ubuntu/deploy.sh
